apiVersion: v2
name: teleflow
description: TeleFlow Platform — Business & Software as Code (instancia por organismo, ADR-005)
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: rabbitmq
    version: "14.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
